packages:
  - packages/hydration/
  - packages/prerender/
  - packages/headings/
  - packages/images/
  - packages/mdx/
  - packages/excerpt/
  - packages/feed/
  - packages/icons/
  - packages/pages/
  - packages/prism/
  - packages/iles/
  - packages/pwa/
  - playground/the-vue-point/
  - docs
catalog:
  vite: https://pkg.pr.new/voidzero-dev/vite-plus/@voidzero-dev/vite-plus-core@eadfb3dec203530d065ae4390288b029108d5baf
  vite-plus: https://pkg.pr.new/voidzero-dev/vite-plus@eadfb3dec203530d065ae4390288b029108d5baf
